export const WEATHER_SCENE_PROFILES = Object.freeze({
  'clear-day': { icon: '☀️', label: '맑고 선명한 하늘', detail: '구름이 거의 없어 태양빛이 또렷합니다.' },
  'clear-night': { icon: '🌙', label: '맑은 밤', detail: '구름이 거의 없는 잔잔한 밤하늘입니다.' },
  'partly-cloudy-day': { icon: '🌤️', label: '구름 사이로 맑음', detail: '햇빛 사이로 구름이 천천히 지나갑니다.' },
  'partly-cloudy-night': { icon: '☁️', label: '구름 조금 낀 밤', detail: '옅은 구름이 밤하늘을 지나갑니다.' },
  'mostly-cloudy-day': { icon: '🌥️', label: '구름 많은 낮', detail: '구름 사이로 부드러운 낮빛이 남아 있습니다.' },
  'mostly-cloudy-night': { icon: '☁️', label: '구름 많은 밤', detail: '두꺼운 구름이 밤하늘의 빛을 낮춥니다.' },
  overcast: { icon: '☁️', label: '짙게 흐림', detail: '낮은 구름층이 하늘을 고르게 덮고 있습니다.' },
  humid: { icon: '🌫️', label: '습한 흐림', detail: '높은 습도로 대기의 대비가 낮아졌습니다.' },
  windy: { icon: '💨', label: '바람 부는 하늘', detail: '강한 바람을 따라 구름이 빠르게 흐릅니다.' },
  drizzle: { icon: '🌦️', label: '빗방울', detail: '성기고 가는 물방울이 간헐적으로 내립니다.' },
  'light-rain': { icon: '🌦️', label: '약한 비', detail: '가느다란 빗줄기가 잔잔하게 이어집니다.' },
  'moderate-rain': { icon: '🌧️', label: '보통 비', detail: '원근감 있는 빗줄기와 젖은 공기가 보입니다.' },
  'heavy-rain': { icon: '🌧️', label: '강한 비', detail: '굵고 빠른 빗줄기로 먼 시야가 낮아집니다.' },
  shower: { icon: '🌦️', label: '소나기', detail: '짧고 밀도 높은 빗줄기가 쏟아집니다.' },
  'violent-shower': { icon: '⛈️', label: '강한 소나기', detail: '짙은 구름 아래 거센 빗줄기가 이어집니다.' },
  sleet: { icon: '🌨️', label: '비와 눈', detail: '차가운 빗방울과 작은 눈 입자가 섞여 내립니다.' },
  'light-snow': { icon: '🌨️', label: '눈날림', detail: '작은 눈 입자가 바람을 따라 천천히 날립니다.' },
  snow: { icon: '🌨️', label: '눈', detail: '눈송이가 꾸준히 내려 시야가 부드럽습니다.' },
  'heavy-snow': { icon: '❄️', label: '강한 눈', detail: '큰 눈송이가 촘촘하게 내려 시야가 낮습니다.' },
  storm: { icon: '⛈️', label: '뇌우', detail: '짙은 구름과 번개, 강한 비가 나타납니다.' },
  sunset: { icon: '🌅', label: '노을빛 하늘', detail: '낮은 태양이 구름 가장자리를 따뜻하게 물들입니다.' },
})
